### ISSUE TITLE
docs: specify that the RPC endpoint is HTTP/S

### ISSUE THREAD

**Issue by onbjerg** [mds1/convex-shutdown-simulation#17]
When https://github.com/gakonst/foundry/pull/1003 is merged Forge will support WebSocket and IPC endpoints which should (in theory, at least) significantly speed up forking, since instead of closing and re-opening the RPC at every request, we would keep the connection alive.

As a sidenote, would it make sense to try and compare with a WebSocket endpoint as well? IPC might be a bit too much.

**Comment by mds1** [comment]
If we just change the below bullet to this, do you think that would be sufficient?

```diff
- - "Remote RPC" benchmarks used Alchemy as the RPC provider.
+ - "Remote RPC" benchmarks used Alchemy as the RPC provider, connected over HTTPS.
 ```

I am curious to see how performance compares between websockets and HTTPS. I'm not sure offhand if ganache and hardhat support it, but if so maybe we can add a second benchmark comparing those three over websockets?

**Comment by onbjerg** [comment]
Yeah, that's fine.

And yeah, I agree - if they support it, we should benchmark and compare. Otherwise, it's probably not a fair comparison :smile:

**Comment by mds1** [comment]
Just pushed 2b13971 which updates the docs, created https://github.com/mds1/convex-shutdown-simulation/issues/18 to track websocket benchmarks investigation/support!

**Comment by mds1** [comment]
Forgot to address IPC: I don't think I've ever come across any real usage/support of IPC either from dev framework or node operators like Infura and Alchemy. (I've also never really looked for it, so I could be wrong). But given that, it doesn't seem worth considering here

**Comment by meetmangukiya** [comment]
Yeah, I don't think IPC is usable out of local fs. So node operators likely won't have any such support.
