### ISSUE TITLE
Out of gas exception when running simulation on Ganache

### ISSUE THREAD

**Issue by dtr0x** [mds1/convex-shutdown-simulation#20]
The transaction runs out of gas (hits block limit of 30M) during simulation with Ganache (I am using Alchemy as a node provider). 
script output:

    $  ./scripts/convex.ganache.ts
    yarn run v1.22.15
    Setting up Ganache...
      eth_chainId
      eth_chainId
      eth_call
      eth_accounts
      eth_sendTransaction
  
        Transaction: 0x22ba0b17256c047bf139d53b98a6cdbb8a1bee5ec10e1573883588c805e5c820
        Contract created: 0x324c828fbc98e722afd73ec91fbf4263eeccb0dc
        Gas usage: 64323
        Block number: 14121829
        Block time: Thu May 19 2022 18:26:28 GMT-0400 (Eastern Daylight Saving Time)
  
      eth_chainId
      eth_getTransactionReceipt
      eth_blockNumber
      eth_chainId
      eth_sendTransaction
  
        Transaction: 0xf9f9c5a0f511df85a01319364f0cfd157130c290eaf06fd89b263e43777a0245
        Contract created: 0xd62f3dfaf07eb471fbd4ab88bfe2c6c8a7dc8b3c
        Gas usage: 64323
        Block number: 14121830
        Block time: Thu May 19 2022 18:26:29 GMT-0400 (Eastern Daylight Saving Time)
  
      eth_chainId
      eth_getTransactionReceipt
      evm_addAccount
      personal_unlockAccount
    setup-ganache: 3.101s
  
    Simulating shutdown...
      eth_sendTransaction
      
        Transaction: 0x8617941537d4f6ddd9934752b93cbf7b335969f1c87956ccbfb110a018aeaaf9
        Gas usage: 30000000
        Block number: 14121831
        Block time: Thu May 19 2022 18:26:29 GMT-0400 (Eastern Daylight Saving Time)
        Runtime error: out of gas

I replicated the logic using Brownie with the same network parameters, but increased the block gas limit to 100M, and found it used around 60M gas:
```
Running 'scripts/sim.py::main'...
Executing system shutdown...
Transaction sent: 0x3007e01e625dd6e40d30890496ae5defc3206145de1636a7ee079f96b988d536
  Gas price: 0.0 gwei   Gas limit: 100000000   Nonce: 1
  Booster.shutdownSystem confirmed   Block: 14445963   Gas used: 60707716 (60.71%)
```

It would be great to know why my results differ from what's given in the readme.

**Comment by mds1** [comment]
PR https://github.com/mds1/convex-shutdown-simulation/pull/15 and its code comments explain why this happens for ganache, perhaps brownie has a similar issue?

**Comment by dtr0x** [comment]
I added the change from this pull request and I get the expected output now. Since brownie also uses ganache as its default ethereum interface, this is an issue with ganache forked chains (as described in the PR). Closing.
